### ISSUE TITLE
Enhancement Issue

### ISSUE THREAD

**Issue by am11piya** [AbhirupSinha/HousingPricePredictor#2]
The UI is not interesting enough. The color scheme is insipid and visually unappealing.
 @AbhirupSinha 
![before](https://user-images.githubusercontent.com/39159042/39870631-b6219a66-547f-11e8-98e8-0748a81b6b61.png)

**Comment by AbhirupSinha** [comment]
Issue fixed @am11piya .
![after](https://user-images.githubusercontent.com/28302531/39870725-fc733ace-547f-11e8-8a33-3e7e6a006700.png)
